db.createCollection('users')
db.users.createIndex({ id: 1 }, { unique: true })
db.createCollection('messages')
db.messages.createIndex({ id: 1 }, { unique: true })
db.messages.createIndex({ to: 1 })
db.messages.createIndex({ from: 1 })
db.createCollection('chats')
db.chats.createIndex({ id: 1 }, { unique: true })
db.chats.createIndex({ members: 1 })
db.createCollection('invites')
db.invites.createIndex({ id: 1 }, { unique: true })
db.invites.createIndex({ to: 1 })
db.invites.createIndex({ from: 1 })

var auth_db = db.getSiblingDB('auth_db')
auth_db.createCollection('users')
auth_db.users.createIndex({ id: 1 }, { unique: true })
auth_db.users.createIndex({ phone: 1 }, { unique: true, sparse: true })
auth_db.users.createIndex({ email: 1 }, { unique: true, sparse: true })
